# Generated by Django 3.2 on 2021-04-30 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='user_to',
            new_name='use_to',
        ),
    ]
